"""Rule-specific engine bridge abstract base class and unconfigured default."""

from __future__ import annotations

from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any

from battlelab.core.errors import CapabilityNotSupportedError
from battlelab.core.models import (
    BotArtifact,
    MatchOutcome,
    MatchResult,
    MatchSpec,
)
from battlelab.official.models import CommandResult, NormalizedReplay


class OfficialEngineBridge(ABC):
    """Abstract interface defining the rule-specific engine contract for the official SDK."""

    @abstractmethod
    def validate_spec(self, spec_data: dict[str, Any]) -> tuple[bool, str]:
        """Validate whether a game spec satisfies official engine requirements."""
        ...

    @abstractmethod
    def probe_sdk(self) -> dict[str, Any]:
        """Probe the official SDK installation, version, and supported features."""
        ...

    @abstractmethod
    def discover_maps(self) -> list[str]:
        """Discover official competition maps."""
        ...

    @abstractmethod
    def validate_bot_compatibility(self, bot_artifact: BotArtifact) -> tuple[bool, str]:
        """Check whether a bot artifact adheres to official packaging and language requirements."""
        ...

    @abstractmethod
    def build_or_prepare_artifact(self, source_path: Path, output_dir: Path) -> dict[str, Any]:
        """Build or prepare a bot artifact into runnable official bot package."""
        ...

    @abstractmethod
    def build_match_command(
        self,
        spec: MatchSpec,
        bot_a: BotArtifact,
        bot_b: BotArtifact,
        work_dir: Path,
    ) -> list[str]:
        """Construct the subprocess argv list for executing an official match."""
        ...

    @abstractmethod
    def parse_match_result(
        self,
        spec: MatchSpec,
        command_result: CommandResult,
        work_dir: Path,
    ) -> MatchResult:
        """Parse engine CLI output and exit codes into a typed MatchResult."""
        ...

    @abstractmethod
    def locate_replay(self, spec: MatchSpec, work_dir: Path) -> Path | None:
        """Locate the official replay file generated by the engine run."""
        ...

    @abstractmethod
    def parse_replay(self, replay_path: Path) -> NormalizedReplay:
        """Parse the raw official replay file into a NormalizedReplay."""
        ...

    @abstractmethod
    def normalize_outcome(self, raw_outcome: Any) -> MatchOutcome:
        """Map official match outcome to platform MatchOutcome."""
        ...


class UnconfiguredOfficialBridge(OfficialEngineBridge):
    """Default production bridge that fails closed pending official SDK release."""

    def validate_spec(self, spec_data: dict[str, Any]) -> tuple[bool, str]:
        return False, "Official competition game specification not completed."

    def probe_sdk(self) -> dict[str, Any]:
        raise CapabilityNotSupportedError(
            "probe_sdk", "official", "Official SDK not released or configured."
        )

    def discover_maps(self) -> list[str]:
        return []

    def validate_bot_compatibility(self, bot_artifact: BotArtifact) -> tuple[bool, str]:
        return False, "Official bot packaging specification unknown pending SDK release."

    def build_or_prepare_artifact(self, source_path: Path, output_dir: Path) -> dict[str, Any]:
        raise CapabilityNotSupportedError(
            "build_or_prepare_artifact", "official", "Official build toolchain unknown."
        )

    def build_match_command(
        self,
        spec: MatchSpec,
        bot_a: BotArtifact,
        bot_b: BotArtifact,
        work_dir: Path,
    ) -> list[str]:
        raise CapabilityNotSupportedError(
            "build_match_command",
            "official",
            "Official engine command line structure unconfigured.",
        )

    def parse_match_result(
        self,
        spec: MatchSpec,
        command_result: CommandResult,
        work_dir: Path,
    ) -> MatchResult:
        raise CapabilityNotSupportedError(
            "parse_match_result", "official", "Official engine output parser unconfigured."
        )

    def locate_replay(self, spec: MatchSpec, work_dir: Path) -> Path | None:
        return None

    def parse_replay(self, replay_path: Path) -> NormalizedReplay:
        raise CapabilityNotSupportedError(
            "parse_replay", "official", "Official replay schema unknown."
        )

    def normalize_outcome(self, raw_outcome: Any) -> MatchOutcome:
        return MatchOutcome.INFRASTRUCTURE_FAILURE
